alias fakeSmtp='sudo python -m smtpd -n -c DebuggingServer localhost:25' 
alias server='python -m http.server $1'
alias gcm='git commit -m $1'
alias gcam='git commit -am $1'
alias s='startx'
alias shutdown='sudo shutdown' 
alias poweroff='sudo poweroff'
